// apps/portal/src/app/apps/todo/todo.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  IonContent,
  IonList,
  IonItem,
  IonCheckbox,
  IonLabel,
  IonButton,
  IonInput,
  IonIcon,
  IonItemSliding,
  IonItemOptions,
  IonItemOption,
  IonToolbar,
  IonHeader,
  IonTitle,
  IonBackButton,
  IonButtons,
} from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import { trashOutline, addOutline, arrowBackOutline } from 'ionicons/icons';
import { TodoService } from './todo.service';
import type { Todo } from '@personal-ai-os/shared';

@Component({
  selector: 'app-todo',
  standalone: true,
  imports: [
    FormsModule,
    IonContent,
    IonList,
    IonItem,
    IonCheckbox,
    IonLabel,
    IonButton,
    IonInput,
    IonIcon,
    IonItemSliding,
    IonItemOptions,
    IonItemOption,
    IonToolbar,
    IonHeader,
    IonTitle,
    IonBackButton,
    IonButtons,
  ],
  template: `
    <ion-header>
      <ion-toolbar>
        <ion-buttons slot="start">
          <ion-back-button defaultHref="/home"></ion-back-button>
        </ion-buttons>
        <ion-title>Todo</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content>
      <ion-list>
        @for (todo of todoService.todos(); track todo.id) {
          <ion-item-sliding>
            <ion-item>
              <ion-checkbox
                slot="start"
                [checked]="todo.done"
                (ionChange)="toggle(todo)"
              ></ion-checkbox>
              <ion-label [class.line-through]="todo.done" [class.opacity-40]="todo.done">
                {{ todo.title }}
              </ion-label>
            </ion-item>
            <ion-item-options side="end">
              <ion-item-option color="danger" (click)="remove(todo.id)">
                <ion-icon slot="icon-only" name="trash-outline"></ion-icon>
              </ion-item-option>
            </ion-item-options>
          </ion-item-sliding>
        }
      </ion-list>

      <div class="flex gap-2 p-4">
        <ion-input
          [(ngModel)]="newTitle"
          placeholder="Add a task…"
          class="flex-1 border border-gray-200 rounded-lg px-3"
          (keyup.enter)="add()"
        ></ion-input>
        <ion-button (click)="add()" [disabled]="!newTitle.trim()">
          <ion-icon slot="icon-only" name="add-outline"></ion-icon>
        </ion-button>
      </div>
    </ion-content>
  `,
})
export class TodoComponent {
  readonly todoService = inject(TodoService);
  newTitle = '';

  constructor() {
    addIcons({ trashOutline, addOutline, arrowBackOutline });
    void this.todoService.loadAll().catch((err) => console.error('loadAll failed', err));
  }

  add(): void {
    const title = this.newTitle.trim();
    if (!title) return;
    void this.todoService.create(title).catch((err) => console.error('create failed', err));
    this.newTitle = '';
  }

  toggle(todo: Todo): void {
    void this.todoService
      .update(todo.id, { done: !todo.done })
      .catch((err) => console.error('update failed', err));
  }

  remove(id: number): void {
    void this.todoService.remove(id).catch((err) => console.error('remove failed', err));
  }
}

// app/apps/todo/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import {
  IonContent,
  IonList,
  IonItem,
  IonCheckbox,
  IonLabel,
  IonButton,
  IonInput,
  IonIcon,
  IonItemSliding,
  IonItemOptions,
  IonItemOption,
  IonToolbar,
  IonHeader,
  IonTitle,
  IonButtons,
} from '@ionic/react';
import { trashOutline, addOutline, arrowBackOutline } from 'ionicons/icons';
import { useTodos } from '../../../lib/use-todos';

export default function TodoPage() {
  const router = useRouter();
  const { todos, add, toggle, remove } = useTodos();
  const [newTitle, setNewTitle] = useState('');

  const handleAdd = () => {
    const title = newTitle.trim();
    if (!title) return;
    void add(title).catch((err) => console.error('create failed', err));
    setNewTitle('');
  };

  return (
    <>
      <IonHeader>
        <IonToolbar>
          <IonButtons slot="start">
            <IonButton onClick={() => router.push('/home')}>
              <IonIcon slot="icon-only" icon={arrowBackOutline} />
            </IonButton>
          </IonButtons>
          <IonTitle>Todo</IonTitle>
        </IonToolbar>
      </IonHeader>

      <IonContent>
        <IonList>
          {todos.map((todo) => (
            <IonItemSliding key={todo.id}>
              <IonItem>
                <IonCheckbox
                  slot="start"
                  checked={todo.done}
                  onIonChange={() =>
                    void toggle(todo).catch((err) => console.error('update failed', err))
                  }
                />
                <IonLabel className={todo.done ? 'line-through opacity-40' : ''}>
                  {todo.title}
                </IonLabel>
              </IonItem>
              <IonItemOptions side="end">
                <IonItemOption
                  color="danger"
                  onClick={() =>
                    void remove(todo.id).catch((err) => console.error('remove failed', err))
                  }
                >
                  <IonIcon slot="icon-only" icon={trashOutline} />
                </IonItemOption>
              </IonItemOptions>
            </IonItemSliding>
          ))}
        </IonList>

        <div className="flex gap-2 p-4">
          <IonInput
            value={newTitle}
            placeholder="Add a task…"
            className="flex-1 border border-gray-200 rounded-lg px-3"
            onIonInput={(e) => setNewTitle(e.detail.value ?? '')}
            onKeyUp={(e) => {
              if (e.key === 'Enter') handleAdd();
            }}
          />
          <IonButton onClick={handleAdd} disabled={!newTitle.trim()}>
            <IonIcon slot="icon-only" icon={addOutline} />
          </IonButton>
        </div>
      </IonContent>
    </>
  );
}
